version: "3.4"

services:
  # Create a PHP container thanks to the Dockerfile
  php:
    build:
      context: .
      target: symfony_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    container_name: php
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      DATABASE_URL: mysql://${MYSQL_USER:-user}:${MYSQL_PASSWORD:-userPa$$w0rd}@database:3306/${MYSQL_DATABASE:-name_of_your_database}
      SYMFONY_VERSION: ''

# Create Caddy (server) container thanks to the Dockerfile   
  caddy:
    build:
      context: .
      target: symfony_caddy
    container_name: caddy
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

#Create a container for the database
  database:
      image: mysql
      container_name: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: unless-stopped
      ports:
        - 3307:3307
      environment:
        MYSQL_DATABASE: graphql
        MYSQL_ROOT_PASSWORD: passion
        MYSQL_USER: damien
        MYSQL_PASSWORD: passion
        # Create a directory at the root of the project and push the content of /var/lib/mysql inside
      volumes:
      - .docker/data/db:/var/lib/mysql

# Create a contenair for phpmyadmin        
  phpmyadmin:
      depends_on:
        - database
      image: phpmyadmin
      container_name: pma
      restart: always
      ports:
        - 8081:80
      environment:
        PMA_HOST: database
        PMA_PORT: 3306
      links:
        - database


volumes:
  caddy_data:
  caddy_config:

###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
